name: wincare_modules
description: "WinCare modules"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_bluetooth_printer: ^2.19.0
  get: ^4.7.2
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/roboto/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
  module:
    androidX: true
    androidPackage: com.wincommerce.wincare.wincare_modules
    iosBundleIdentifier: com.wincommerce.wincare.wincareModules
