name: wincare_modules
description: "WinCare modules"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  #flutter_bluetooth_printer: ^2.19.0
  flutter_bluetooth_printer:
    git:
      url: https://github.com/uytb-masan/flutter_bluetooth_printer_plugin.git
      path: packages/flutter_bluetooth_printer
      ref: main
  get: ^4.7.2
  intl: ^0.18.1
  shared_preferences: ^2.5.3
  qr_flutter: ^4.0.0
  auto_size_text: ^3.0.0
  #mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/roboto/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
  module:
    androidX: true
    androidPackage: com.wincommerce.wincare.wincare_modules
    iosBundleIdentifier: com.wincommerce.wincare.wincareModules
